services:
  server:
    build: ./server
    image: laksh2611/expense-server:latest  
    container_name: expenseManagement-server
    expose:
      - "5012"          # visible to other containers
    env_file:
      - ./server/.env
    restart: always
  client:
    build: ./client
    image: laksh2611/expense-client:latest
    container_name: expenseManagement-client
    ports:
      - "80:80"         # server_ip:80 â†’ client container 80 (Nginx)
    depends_on:
      - server
    restart: always
