services:
  server:
    image: laksh2611/expense-server:latest
    container_name: expenseManagement-server
    ports:
      - "5012:5012"
    env_file:
      - ./server/.env
    restart: always

  client:
    image: laksh2611/expense-client:latest
    container_name: expenseManagement-client
    ports:
      - "8005:80"
    depends_on:
      - server
    restart: always
